config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [ :new, :create ]
  end
  resources :doses, only: [ :show, :edit, :update, :destroy  ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :name, presence: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
  
  belongs_to :cocktail
  belongs_to :ingredient

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: :true

  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.create(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <h2>Edit cocktail</h2>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.submit "Edit cocktail!", class: "btn btn-primary" %>
  <%end%>
</div>

app/views/cocktails/index.html.erb
<div class="main mb-6" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.mtl.org/sites/default/files/styles/playlist_banner_big/public/2020-04/45441.jpg?h=f8c4e648&itok=UihvhxLK);">
  <div class="container">
    <h1>Because you deserve it <strong></h1>
    <p>Change your life and learn to create your drinks.</p>
    <%= link_to "Create a drink", new_cocktail_path, class:"btn btn-outline-light" %>
  </div>
</div>
<div class="container">
  <h1 class="h1title">Listed coctails</h1>
  <div class="cards-grid">
    <%@cocktails.each do |cocktail|%>
      <% if cocktail.photo.attached? %>
        <div class="drinkcard" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
      <%else%> 
         <div class="card">
      <%end%>
        <div class="info">
          <h3><%= link_to cocktail.name, cocktail_path(cocktail)%></h3>
        </div>
      </div>
    <%end%>
    
<!-- for face detection -->
  </div>
  
 </div>

app/views/cocktails/new.html.erb
<div class="container">
  <h2>New cocktail</h2>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Create cocktail!", class: "btn btn-primary" %>
  <%end%>
</div>

app/views/cocktails/show.html.erb
<div class="showimg mb-6" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
  <h2><%=@cocktail.name%></h2>
    <div class="d-flex">
    <i><%= link_to "Edit", edit_cocktail_path, class:"far fa-edit" %></i>
  </div>
</div>
<div class="container mt-3 pads">
  <h2 class="h1title">What you will need</h2>
  <% @cocktail.doses.each do |dose| %>
    <p><i class="fas fa-cocktail"></i><b><%=dose.ingredient.name%></b> - <%= dose.description %>   <i class="nanda"><%= link_to "", dose_path(dose), method: :delete, class:"fas fa-trash" %></i></p>
  <% end %>
  <%= link_to 'Add a dose', new_cocktail_dose_path(@cocktail), class:"btn btn-outline-dark" %>
  <%= link_to "Delete this cocktail", cocktail_path(@cocktail), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-dark"  %>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h2>Let the world know!</h2>
  <%= simple_form_for [ @cocktail, @dose ] do |f| %>
    <%= f.association :ingredient%>
    <%= f.input :description %>
    <%= f.submit "Submit doses", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
  <div class="flex-wrapper">
    <div class="page-cont">
    <div class="banner sticky-top">
      <p><%= link_to "Yopparai.com", cocktails_path %></p>
    </div>
    <%= yield %>
    </div>
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright"></div>
    </div>
</div>
  </body>
</html>